name: CI
on: [push, pull_request]

jobs:
  openapi-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g @stoplight/spectral-cli
      - run: spectral lint openapi.yml

  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d mock
      - name: Wait for Prism
        run: |
          for i in {1..20}; do
            code=$(curl -s -o /dev/null -w '%{http_code}' -H 'Authorization: Bearer demo-token' http://127.0.0.1:8080/healthz || true)
            [ "$$code" = "200" ] && exit 0
            sleep 1
          done
          echo "Prism not ready"; exit 1
      - name: Webhook 204
        run: |
          code=$(curl -s -o /dev/null -w '%{http_code}' -i -X POST 'http://127.0.0.1:8080/webhook' \
            -H 'Authorization: Bearer demo-token' \
            -H 'Content-Type: application/json' \
            -H 'X-GitHub-Event: issues' \
            -H 'X-GitHub-Delivery: 00000000-0000-0000-0000-000000000000' \
            -H 'X-Hub-Signature-256: sha256=aee73876dc0cbb71cf5122dd391733e28fabc009eba54be1a2066cb1e92c81d1' \
            -d '{"action":"opened","issue":{"id":1,"number":1,"title":"hello","state":"open","user":{"id":1,"login":"alice"}},"repository":{"id":1,"full_name":"you/your-repo"},"sender":{"id":1,"login":"alice"}}')
          [ "$$code" = "204" ]
      - run: docker compose down
