name: CI
on:
  push:
  pull_request:

jobs:
  openapi-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Spectral
        run: npm i -g @stoplight/spectral-cli
      - name: Lint OpenAPI
        run: spectral lint openapi.yml
