services:
  mock:
    image: stoplight/prism:5
    # platform: linux/amd64   
    volumes:
      - ./openapi.yml:/work/openapi.yml:ro
    command: ["mock","-h","0.0.0.0","-p","8080","/work/openapi.yml"]
    ports:
      - "${PORT:-8080}:8080"
